
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lolos
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
public class FeedbackPage extends javax.swing.JFrame {

    /**
     * Creates new form FeedbackPage
     */
    private int customerId; // Store the customer_id for the logged-in user
    private int userId;

public FeedbackPage(int userId) {
    this.userId = userId;
    this.customerId = getCustomerIdForUser(userId);  // Store the customer_id based on the passed userId
    if (this.customerId == -1) {
        JOptionPane.showMessageDialog(this, "No customer found for userId: " + userId);
        return; // Prevent further execution if customer is not found
    }
    initComponents();
    // Proceed with other logic (e.g., displaying feedback)
}
    

private int getCustomerIdForUser(int userId) {
    int customerId = -1;  // Default value indicating "not found"
    try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tastyhub", "root", "queen haya")) {
        // Use the passed userId to query for the customerId
        String query = "SELECT customer_id FROM customer WHERE user_id = ?";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setInt(1, userId);  // Set the user_id parameter for the query
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            customerId = rs.getInt("customer_id");  // Retrieve the customer_id from the result
            System.out.println("Found customerId: " + customerId);  // Debugging output
        } else {
            System.out.println("No customer found for userId: " + userId);  // Debugging output
        }

        rs.close();
        pst.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error fetching customer_id: " + e.getMessage());
    }
    return customerId;  // Return the customer_id (or -1 if not found)
}
    
private void saveFeedbackToDatabase(String feedback) {
    if (customerId == -1) {
        JOptionPane.showMessageDialog(this, "Cannot save feedback: Customer ID is missing.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tastyhub", "root", "queen haya")) {
        String query = "INSERT INTO feedback (customer_id, message) VALUES (?, ?)";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setInt(1, customerId);
        pst.setString(2, feedback);
        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Feedback submitted successfully!");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error saving feedback: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(130, 80, 156));
        jTextArea1.setRows(5);
        jTextArea1.setText("Write your feedback or review here...");
        jTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextArea1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 358, 74));

        jButton1.setBackground(new java.awt.Color(157, 51, 210));
        jButton1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 90, -1));

        jButton2.setBackground(new java.awt.Color(157, 51, 210));
        jButton2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 90, -1));

        jButton3.setBackground(new java.awt.Color(157, 51, 210));
        jButton3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Import Pictures");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 150, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 100, 60));

        jPanel1.setBackground(new java.awt.Color(242, 230, 248));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(95, 65, 105));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Feedback & Reviews");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    String feedback = jTextArea1.getText().trim();

    if (feedback.isEmpty() || feedback.equals("Write your feedback or review here...")) {
        JOptionPane.showMessageDialog(this, "Please write something first.", "Empty Feedback", JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (feedback.length() > 100) {
        JOptionPane.showMessageDialog(this, "Feedback too long! Please keep it under 100 characters.", "Input Too Long", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Save feedback
    saveFeedbackToDatabase(feedback);
    jTextArea1.setText(""); // Clear input

    }//GEN-LAST:event_jButton2ActionPerformed

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    HomePage home = new HomePage(userId);  // Pass userId here
    home.setVisible(true);
    dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextArea1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea1MousePressed
    if (jTextArea1.getText().equals("Write your feedback or review here...")) {
        jTextArea1.setText("");
    }
   
    }//GEN-LAST:event_jTextArea1MousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Select an image");
    fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Image files", "jpg", "png", "gif"));

    int result = fileChooser.showOpenDialog(this);

    if (result == JFileChooser.APPROVE_OPTION) {
        File selectedFile = fileChooser.getSelectedFile();

        // Basic validation
        if (!selectedFile.exists() || !selectedFile.isFile()) {
            JOptionPane.showMessageDialog(this, "Invalid file selected.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String imagePath = selectedFile.getAbsolutePath();
        displayImage(imagePath);
    }
                               
    }//GEN-LAST:event_jButton3ActionPerformed

private void displayImage(String imagePath) {
    try {
        ImageIcon imageIcon = new ImageIcon(imagePath);
        Image image = imageIcon.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);
        imageIcon = new ImageIcon(image);
        jLabel2.setIcon(imageIcon);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error displaying the image: " + e.getMessage());
    }
}

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
