/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author fatimaalnasser
 */

import java.awt.HeadlessException;
import java.awt.Image;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.SQLIntegrityConstraintViolationException;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.*;

public class ordermanagment extends javax.swing.JFrame {

    /**
     * Creates new form ordermanagment
     */
    
    private int loggedInUserId;
  
    
    public ordermanagment(int loggedInUserId) {
        this.loggedInUserId = loggedInUserId;
        initComponents();
        jButton5ActionPerformed(null); // Initial load of orders
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        jLabel1.setText("Add New Order");

        jTextField1.setText("jTextField1");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setBackground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Order Managment");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("85074319-3c96-4938-99fb-d214aa1cc1da.JPG")));
        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(242, 230, 248));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(76, 39, 76));
        jLabel4.setText("Order Managment");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jButton3.setBackground(new java.awt.Color(233, 233, 250));
        jButton3.setText("Update Status");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 120, 30));

        jButton4.setBackground(new java.awt.Color(233, 233, 250));
        jButton4.setText("Cancel Order");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 120, 30));

        jButton5.setBackground(new java.awt.Color(233, 233, 250));
        jButton5.setText("Refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 120, 30));

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"101", "John", "Pending"},
                {"102", "Williams", "Shipped"},
                {"103", "Smith", "Delivered"},
                {null, null, null}
            },
            new String [] {
                "Order ID", "Custumer", "Status"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 320, 170));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel5.setText("Order ID:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 60, -1));
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 130, -1));

        jButton6.setBackground(new java.awt.Color(204, 204, 255));
        jButton6.setText("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        jButton7.setBackground(new java.awt.Color(233, 233, 250));
        jButton7.setText("Add new order");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 120, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    int row = jTable2.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select an order first.");
        return;
    }

    String[] options = {"Pending", "Finished"};
    String newStatus = (String) JOptionPane.showInputDialog(this, "Select new status:",
            "Update Status", JOptionPane.QUESTION_MESSAGE, null, options, options[0]);

    if (newStatus != null) {
        int orderId = Integer.parseInt(jTable2.getValueAt(row, 0).toString());
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tastyhub", "root", "queen haya");
            String updateQuery = "UPDATE CUSTOMER_ORDER SET status=? WHERE order_id=?";
            PreparedStatement pst = con.prepareStatement(updateQuery);
            pst.setString(1, newStatus);
            pst.setInt(2, orderId);
            pst.executeUpdate();
            pst.close();
            con.close();
            JOptionPane.showMessageDialog(this, "Status updated successfully.");
            jButton5ActionPerformed(null); // Refresh
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error updating status: " + e.getMessage());
        }
    
}

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    // TODO add your handling code here:
    try {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tastyhub", "root", "queen haya");
        String query = "SELECT co.order_id, CONCAT(u.first_name, ' ', u.last_name) AS customer_name, co.status "
                     + "FROM CUSTOMER_ORDER co "
                     + "JOIN CUSTOMER c ON co.customer_id = c.customer_id "
                     + "JOIN USER u ON c.user_id = u.user_id";  // Join USER table to get customer name
        PreparedStatement pst = con.prepareStatement(query);
        ResultSet rs = pst.executeQuery();

        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0); // Clear current data

        while (rs.next()) {
            Object[] row = {
                rs.getInt("order_id"),
                rs.getString("customer_name"),  // Displays full name of the customer
                rs.getString("status")
            };
            model.addRow(row);
        }

        rs.close();
        pst.close();
        con.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Failed to load orders: " + e.getMessage());
    }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    // TODO add your handling code here:
    // Create an instance of the StaffHomeFrame
    new StaffHomeFrame(loggedInUserId).setVisible(true);

    // Close the current Order Management frame
    this.dispose(); 

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    int row = jTable2.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select an order to cancel.");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to cancel this order?", "Confirm", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        int orderId = Integer.parseInt(jTable2.getValueAt(row, 0).toString());
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tastyhub", "root", "queen haya");
            String deleteQuery = "DELETE FROM CUSTOMER_ORDER WHERE order_id=?";
            PreparedStatement pst = con.prepareStatement(deleteQuery);
            pst.setInt(1, orderId);
            pst.executeUpdate();
            pst.close();
            con.close();
            JOptionPane.showMessageDialog(this, "Order cancelled.");
            jButton5ActionPerformed(null); // Refresh table
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error cancelling order: " + e.getMessage());
        }
    }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    // Search for an order by ID
    String orderId = jTextField2.getText().trim();
    if (orderId.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter an order ID to search.");
        return;
    }

    try {
        // Refresh the search data
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tastyhub", "root", "queen haya");
        String query = "SELECT co.order_id, u.first_name, u.last_name, co.status "
                     + "FROM CUSTOMER_ORDER co "
                     + "JOIN CUSTOMER c ON co.customer_id = c.customer_id "
                     + "JOIN USER u ON c.user_id = u.user_id "
                     + "WHERE co.order_id = ?";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setString(1, orderId);
        ResultSet rs = pst.executeQuery();

        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0); // Clear current data

        if (rs.next()) {
            Object[] row = {
                rs.getInt("order_id"),
                rs.getString("first_name") + " " + rs.getString("last_name"), // Show full customer name
                rs.getString("status")
            };
            model.addRow(row);
        } else {
            JOptionPane.showMessageDialog(this, "Order not found.");
        }

        rs.close();
        pst.close();
        con.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error searching order: " + e.getMessage());
    }


    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

    // Add new order (implement with dialog or new frame)
    String customerName = JOptionPane.showInputDialog("Enter customer name:");
    String status = JOptionPane.showInputDialog("Enter order status (Pending, Finished):");

    // Validate customer name
    if (customerName == null || customerName.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a valid customer name.");
        return;
    }

    // Generate current date and time for order_date
    LocalDateTime now = LocalDateTime.now();
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    String orderDate = now.format(formatter);  // Format date as "yyyy-MM-dd HH:mm:ss"
    
    // Prompt the user to enter the total amount
    String totalAmountStr = JOptionPane.showInputDialog("Enter total amount for the order:");
    
    // Validate total amount
    double totalAmount = 0;
    try {
        totalAmount = Double.parseDouble(totalAmountStr);  // Convert the string to a double
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid total amount. Please enter a valid number.");
        return;
    }

    try {
        // Find customer based on their name
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tastyhub", "root", "queen haya");

        String checkCustomerQuery = "SELECT c.customer_id FROM CUSTOMER c "
                                  + "JOIN USER u ON c.user_id = u.user_id "
                                  + "WHERE CONCAT(u.first_name, ' ', u.last_name) = ?";
        PreparedStatement checkCustomerPst = con.prepareStatement(checkCustomerQuery);
        checkCustomerPst.setString(1, customerName);
        ResultSet rs = checkCustomerPst.executeQuery();

        int customerId = -1;
        if (rs.next()) {
            customerId = rs.getInt("customer_id");
        } else {
            JOptionPane.showMessageDialog(this, "Customer not found.");
            return;
        }

        // Insert new order into CUSTOMER_ORDER table
        String insertOrderQuery = "INSERT INTO CUSTOMER_ORDER (customer_id, status, order_date, total_amount) "
                                 + "VALUES (?, ?, ?, ?)";
        PreparedStatement insertOrderPst = con.prepareStatement(insertOrderQuery);
        insertOrderPst.setInt(1, customerId);
        insertOrderPst.setString(2, status);
        insertOrderPst.setString(3, orderDate);
        insertOrderPst.setDouble(4, totalAmount);
        insertOrderPst.executeUpdate();
        insertOrderPst.close();
        con.close();

        JOptionPane.showMessageDialog(this, "Order added successfully.");
        jButton5ActionPerformed(null); // Refresh the orders
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error adding order: " + e.getMessage());
    }


    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
