/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author shahadadel
 */

import java.awt.HeadlessException;
import java.awt.Image;
import java.net.URL;  // For the URL class to load the image
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.SQLIntegrityConstraintViolationException;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
public class ReggFrame extends javax.swing.JFrame {

    /**
     * Creates new form ReggFrame
     */
    public ReggFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonJoinNow = new javax.swing.JButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(242, 230, 248));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 3, 54)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(95, 65, 105));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("🍽️ Tasty Hub ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 400, 80));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 3, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(155, 93, 176));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Welcome to Tasty Hub!");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 325, -1));

        jButtonJoinNow.setBackground(new java.awt.Color(157, 51, 210));
        jButtonJoinNow.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jButtonJoinNow.setForeground(new java.awt.Color(255, 255, 204));
        jButtonJoinNow.setText("Join now");
        jButtonJoinNow.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonJoinNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJoinNowActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJoinNow, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 590, 140, 40));

        jRadioButton2.setAutoscrolls(true);
        jRadioButton2.setLabel("Customer");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, -1, -1));

        jRadioButton1.setAutoscrolls(true);
        jRadioButton1.setLabel("Employee");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 2, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(130, 80, 156));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Role");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 50, 30));

        txtPassword.setColumns(20);
        txtPassword.setForeground(new java.awt.Color(153, 153, 153));
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 300, 30));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 2, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(130, 80, 156));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Password");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 90, 30));

        txtPhoneNumber.setColumns(20);
        txtPhoneNumber.setForeground(new java.awt.Color(153, 153, 153));
        txtPhoneNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPhoneNumber.setText("+9965");
        txtPhoneNumber.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 300, 30));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 2, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(130, 80, 156));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Phone Number");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 150, 30));

        txtEmail.setColumns(20);
        txtEmail.setForeground(new java.awt.Color(153, 153, 153));
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmail.setText("@example.com");
        txtEmail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 300, 30));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 2, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(130, 80, 156));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Email");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 50, -1));

        txtUsername.setColumns(20);
        txtUsername.setForeground(new java.awt.Color(153, 153, 153));
        txtUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsername.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 300, 30));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 2, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(130, 80, 156));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Last Name ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 110, -1));

        jLabel8.setFont(new java.awt.Font("Segoe Print", 2, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(130, 80, 156));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Username");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 80, -1));

        jTextField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 120, 30));

        jLabel9.setFont(new java.awt.Font("Segoe Print", 2, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(130, 80, 156));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("First Name ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 110, -1));

        jTextField2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 120, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonJoinNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJoinNowActionPerformed
    try {
        String role = "";
        if (jRadioButton1.isSelected()) {
            role = "employee";
        } else if (jRadioButton2.isSelected()) {
            role = "customer";
        } else {
            JOptionPane.showMessageDialog(this, "Please select a role (Customer or Employee).");
            return;
        }

        // Get input values
        String username = txtUsername.getText().trim();
        String firstName = jTextField2.getText().trim(); // first name
        String lastName = jTextField1.getText().trim();  // last name
        String email = txtEmail.getText().trim();
        String phone = txtPhoneNumber.getText().trim();
        String password = txtPassword.getText().trim();

        // Check for empty fields
        if (username.isEmpty() || firstName.isEmpty() || lastName.isEmpty() || 
            email.isEmpty() || password.isEmpty() || phone.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields!", 
                "Missing Information", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Name should only contain letters
        if (!firstName.matches("[a-zA-Z]+") || !lastName.matches("[a-zA-Z]+")) {
            JOptionPane.showMessageDialog(this, "Names can only contain letters (no numbers or special characters).", 
                "Name Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
            // Username validation
    if (!username.matches("[a-zA-Z0-9_]+")) {
        JOptionPane.showMessageDialog(this, "Username can only contain letters, numbers, and underscores.", "Invalid Username", JOptionPane.ERROR_MESSAGE);
        return;
    }


        // Validate email format
        if (!email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")) {
            JOptionPane.showMessageDialog(this, "Invalid email format!", 
                "Email Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate password length
        if (password.length() < 6) {
            JOptionPane.showMessageDialog(this, "Password must be at least 6 characters long.", 
                "Password Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validate phone number for Saudi numbers
        String saudiPhoneRegex = "^\\+9665[0-9]{8}$";  
        if (!phone.matches(saudiPhoneRegex)) {
            JOptionPane.showMessageDialog(this, 
                "Please enter a valid Saudi phone number (+9665XXXXXXXX)", 
                "Phone Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Database connection
        String url = "jdbc:mysql://localhost:3306/tastyhub"; 
        String dbUser = "root"; 
        String dbPass = "queen haya"; 

        // Check if username already exists
        try (Connection con = DriverManager.getConnection(url, dbUser, dbPass)) {
            String checkUserQuery = "SELECT * FROM user WHERE username = ?";
            PreparedStatement checkUserStmt = con.prepareStatement(checkUserQuery);
            checkUserStmt.setString(1, username);
            ResultSet rs = checkUserStmt.executeQuery();

            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "Username already exists!", "Error", JOptionPane.ERROR_MESSAGE);
                return; // Exit if username is taken
            }

            // Insert into USER table
            String userQuery = "INSERT INTO user (first_name, last_name, username, email, password, phone, user_type) VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = con.prepareStatement(userQuery, Statement.RETURN_GENERATED_KEYS);
            pst.setString(1, firstName);
            pst.setString(2, lastName);
            pst.setString(3, username);
            pst.setString(4, email);
            pst.setString(5, password);
            pst.setString(6, phone);
            pst.setString(7, role);
            pst.executeUpdate();
            
            // Get generated user_id
            rs = pst.getGeneratedKeys();
            int userId = 0;
            if (rs.next()) {
                userId = rs.getInt(1);
            }

            // If role is customer, insert into customer table
            if (role.equals("customer")) {
                // Generate customer_id (You can modify this logic if needed)
                int customerId = userId + 10000; // Example logic to generate customer_id
                
                String custQuery = "INSERT INTO customer (customer_id, user_id, name, email) VALUES (?, ?, ?, ?)";
                PreparedStatement cpst = con.prepareStatement(custQuery);
                cpst.setInt(1, customerId);
                cpst.setInt(2, userId);
                cpst.setString(3, firstName + " " + lastName); // Combine first and last name
                cpst.setString(4, email);
                cpst.executeUpdate();
            } else {
                // Employee logic remains the same
                String salaryInput = JOptionPane.showInputDialog(this, "Enter salary for employee:");
                try {
                    double salary = Double.parseDouble(salaryInput);
                    if (salary <= 0) throw new NumberFormatException();
                    
                    // Generate employee_id (similar to the logic above for customer)
                    int employeeId = userId + 20000;
                    
                    String empQuery = "INSERT INTO employee (employee_id, user_id, salary) VALUES (?, ?, ?)";
                    try (PreparedStatement epst = con.prepareStatement(empQuery)) {
                        epst.setInt(1, employeeId);
                        epst.setInt(2, userId);
                        epst.setDouble(3, salary);
                        epst.executeUpdate();
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Invalid salary entered!", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            // After successful registration, redirect the user
            if (role.equals("customer")) {
                JOptionPane.showMessageDialog(this, "Registration successful!", "Welcome", JOptionPane.INFORMATION_MESSAGE);
                new HomePage(username).setVisible(true);  // Customer goes to HomePage with username
                this.dispose();
            } else {  // Employee
                JOptionPane.showMessageDialog(this, "Registration successful!", "Welcome", JOptionPane.INFORMATION_MESSAGE);
                new StaffHomeFrame().setVisible(true);  // Staff goes to StaffHomeFrame
                this.dispose();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    } catch (HeadlessException ex) {
        JOptionPane.showMessageDialog(this, "Headless Exception: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }

    }//GEN-LAST:event_jButtonJoinNowActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        jRadioButton1.setSelected(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        jRadioButton2.setSelected(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
        txtEmail.requestFocus();
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here
        txtPhoneNumber.requestFocus();
    }//GEN-LAST:event_txtEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReggFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReggFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReggFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReggFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReggFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonJoinNow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
