/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author shahadadel
 */

import java.awt.HeadlessException;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.SQLIntegrityConstraintViolationException;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class StaffAccount extends javax.swing.JFrame {

    /**
     * Creates new form StaffAccount
     */
    private int userId;

    public StaffAccount(int userId) {
    this.userId = userId;
    System.out.println("User ID: " + userId); // Debug: Check if userId is correct
    initComponents();
    loadAccountInfo();
}

    
private void loadAccountInfo() {
    try {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tastyhub", "root", "queen haya");

        // Query to fetch user info along with the associated employee info
        String query = "SELECT u.username, u.email, u.password, u.phone, e.department " +
                "FROM USER u " +
                "JOIN EMPLOYEE e ON u.user_id = e.user_id " +
                "WHERE u.user_id = ?";  // Use the userId passed to the constructor

        PreparedStatement pst = con.prepareStatement(query);
        pst.setInt(1, userId);  // Use the passed userId
        ResultSet rs = pst.executeQuery();

        // Debugging: Check if data is fetched
        System.out.println("Executing query: " + query);
        if (rs.next()) {
            System.out.println("Fetched Data: " + rs.getString("username") + ", " + rs.getString("email"));
            
            // Fill the fields with the existing data
            txtUserId.setText(String.valueOf(userId));  // Set user_id (read-only)
            txtUsername.setText(rs.getString("username"));
            txtEmail.setText(rs.getString("email"));
            txtPhone.setText(rs.getString("phone"));
            txtPassword.setText(rs.getString("password"));
            txtDepartment.setText(rs.getString("department"));
        } else {
            System.out.println("No data found for user_id: " + userId);
        }

        rs.close();
        pst.close();
        con.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error loading account: " + e.getMessage());
    }
}

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtDepartment = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtUserId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 232, 247));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe Print", 3, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(155, 93, 176));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Account Settings");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 325, -1));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 2, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(130, 80, 156));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 80, -1));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 2, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(130, 80, 156));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Email");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 50, -1));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 2, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(130, 80, 156));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Phone Number");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 130, 30));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 2, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(130, 80, 156));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Password");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 90, 30));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 2, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(130, 80, 156));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Department ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 110, 30));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 70, 20));

        jButton2.setLabel("Change");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 110, 40));
        jPanel1.add(txtDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 250, 30));
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 100, 30));
        txtUsername.getAccessibleContext().setAccessibleName("");

        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 250, 30));
        jPanel1.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 250, 30));
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 250, 30));

        jLabel8.setFont(new java.awt.Font("Segoe Print", 2, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(130, 80, 156));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Username");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 80, -1));

        txtUserId.setEnabled(false);
        jPanel1.add(txtUserId, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Retrieve inputs from the text fields
        String username = txtUsername.getText().trim();
        String email = txtEmail.getText().trim();
        String phone = txtPhone.getText().trim();
        String password = txtPassword.getText().trim();
        String department = txtDepartment.getText().trim();  // Update this to reflect the department

    if (username.isEmpty() || email.isEmpty() || phone.isEmpty() || password.isEmpty() || department.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all fields.");
        return;
    }
    
    if(!department.matches("[a-zA-Z]+")) {
            JOptionPane.showMessageDialog(this, "Department can only contain letters (no numbers or special characters).", 
                "Name Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

    if (!username.matches("^[a-zA-Z0-9_]+$")) {
        JOptionPane.showMessageDialog(this, "Username must only contain letters, numbers, or underscores.", "Invalid Username", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")) {
        JOptionPane.showMessageDialog(this, "Invalid email format.", "Invalid Email", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!phone.matches("^\\+9665\\d{8}$")) {
        JOptionPane.showMessageDialog(this, "Phone must follow Saudi format: +9665XXXXXXXX", "Invalid Phone", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (password.length() < 6) {
        JOptionPane.showMessageDialog(this, "Password must be at least 6 characters.", "Weak Password", JOptionPane.WARNING_MESSAGE);
        return;
    }


        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tastyhub", "root", "queen haya");

            // Update user details in the USER table
            String updateUserQuery = "UPDATE USER SET username = ?, email = ?, password = ?, phone = ? WHERE user_id = ?";
            PreparedStatement pstUser = con.prepareStatement(updateUserQuery);
            pstUser.setString(1, username);
            pstUser.setString(2, email);
            pstUser.setString(3, password);
            pstUser.setString(4, phone);
            pstUser.setInt(5, userId);
            int rowsAffectedUser = pstUser.executeUpdate();

            
            // Update employee details in the EMPLOYEE table
            String updateEmpQuery = "UPDATE EMPLOYEE SET department = ? WHERE user_id = ?";
            PreparedStatement pstEmp = con.prepareStatement(updateEmpQuery);
            pstEmp.setString(1, department);  // This corresponds to the 'department' in EMPLOYEE table
            pstEmp.setInt(2, userId);  // Use the userId passed to the constructor
            int rowsAffectedEmp = pstEmp.executeUpdate();

            // Close resources
            pstUser.close();
            pstEmp.close();
            con.close();

            if (rowsAffectedUser > 0 || rowsAffectedEmp > 0) {
                JOptionPane.showMessageDialog(this, "Account updated successfully!");
                loadAccountInfo();  // Refresh the account info after updating
            } else {
                JOptionPane.showMessageDialog(this, "No changes made.");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Update failed: " + e.getMessage());
        }
   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new StaffHomeFrame(userId).setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffAccount(12344).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDepartment;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtUserId;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
